image: node:latest

stages:
  - build
  - test

dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script:
    - node test.js
  artifacts:
    paths:
      - node_modules/
